import Head from 'next/head'
import { PageHeader } from 'components/PageHeader'
import { RestaurantList } from 'containers/RestaurantList'

function HomePage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader />
      <RestaurantList />
    </div>
  )
}

export default HomePage
